version: "3.5"
services:
    networking-mysql:
        image: mysql:8.0.21
        container_name: networking-mysql
        working_dir: /application
        volumes:
            - networking-mysql:/var/lib/mysql/
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: networking_db
            MYSQL_USER: root
        ports:
            - "2330:3306"
volumes:
    networking-mysql:
        driver: "local"