use networking_db;

SET CHARACTER SET utf8;

DROP TABLE IF EXISTS customer_host;
DROP TABLE IF EXISTS hosts;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS customers;

CREATE TABLE hosts (
	id SERIAL PRIMARY KEY,
	ip VARCHAR(15) NOT NULL,
	mac VARCHAR(17) NOT NULL UNIQUE,
	created_at DATETIME DEFAULT NOW(),
	updated_at DATETIME DEFAULT NOW()
)ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	login VARCHAR(100) NOT NULL UNIQUE,
	password_hash VARCHAR(100) NOT NULL,
	session_id VARCHAR(100) NOT NULL,
	created_at DATETIME DEFAULT NOW(),
	updated_at DATETIME DEFAULT NOW()
)ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE customers (
	id SERIAL PRIMARY KEY,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	second_name VARCHAR(100) NOT NULL,
	created_at DATETIME DEFAULT NOW(),
	updated_at DATETIME DEFAULT NOW()
)ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE customer_host (
	id SERIAL PRIMARY KEY,
	customer_id BIGINT UNSIGNED NOT NULL,
	host_id BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (customer_id) REFERENCES `customers`(id) ON UPDATE CASCADE ON delete CASCADE,
	FOREIGN KEY (host_id) REFERENCES `hosts`(id) ON UPDATE CASCADE ON delete CASCADE
);

SELECT * FROM hosts;